### ISSUE TITLE
Practica de objeto 3D con animación 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-jaciel#1]
[Reporte de objeto 3D con animacion.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-jaciel/files/8352211/Reporte.de.objeto.3D.con.animacion.pdf)
.

**Comment by garaudy12** [comment]
Excelente animación cumple con todos los aspectos de la rúbrica 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
